insert into tbmovimento values
	(null, 'Absorb', 5, 2, 20, 100, 25, ''),
	(null, 'Acid', null, null, null, null, null, ''),
	(null, 'Acid Armor', null, null, null, null, null, ''),
	(null, 'Agility', null, null, null, null, null, ''),
	(null, 'Amnesia', null, null, null, null, null, ''),
	(null, 'Aurora Beam', null, null, null, null, null, ''),
	(null, 'Barrage', null, null, null, null, null, ''),
	(null, 'Barrier', null, null, null, null, null, ''),
	(null, 'Bide', null, null, null, null, null, ''),
	(null, 'Bind', null, null, null, null, null, ''),
	(null, 'Bite', null, null, null, null, null, ''),
	(null, 'Blizzard', null, null, null, null, null, ''),
	(null, 'Body Slam', null, null, null, null, null, ''),
	(null, 'Bone Club', null, null, null, null, null, ''),
	(null, 'Bonemerang', null, null, null, null, null, ''),
	(null, 'Bubble', null, null, null, null, null, ''),
	(null, 'Bubble Beam', null, null, null, null, null, ''),
	(null, 'Clamp', null, null, null, null, null, ''),
	(null, 'Comet Punch', null, null, null, null, null, ''),
	(null, 'Confuse Ray', null, null, null, null, null, ''),
	(null, 'Confusion', null, null, null, null, null, ''),
	(null, 'Constrict', null, null, null, null, null, ''),
	(null, 'Conversion', null, null, null, null, null, ''),
	(null, 'Counter', null, null, null, null, null, ''),
	(null, 'Crabhammer', null, null, null, null, null, ''),
	(null, 'Cut', null, null, null, null, null, ''),
	(null, 'Defense Curl', null, null, null, null, null, ''),
	(null, 'Dig', null, null, null, null, null, ''),
	(null, 'Disable', null, null, null, null, null, ''),
	(null, 'Dizzy Punch', null, null, null, null, null, ''),
	(null, 'Double Kick', null, null, null, null, null, ''),
	(null, 'Double Slap', null, null, null, null, null, ''),
	(null, 'Double Team', null, null, null, null, null, ''),
	(null, 'Double-Edge', null, null, null, null, null, ''),
	(null, 'Dragon Rage', null, null, null, null, null, ''),
	(null, 'Dream Eater', null, null, null, null, null, ''),
	(null, 'Drill Peck', null, null, null, null, null, ''),
	(null, 'Earthquake', null, null, null, null, null, ''),
	(null, 'Egg Bomb', null, null, null, null, null, ''),
	(null, 'Ember', null, null, null, null, null, ''),
	(null, 'Explosion', null, null, null, null, null, ''),
	(null, 'Fire Blast', null, null, null, null, null, ''),
	(null, 'Fire Punch', null, null, null, null, null, ''),
	(null, 'Fire Spin', null, null, null, null, null, ''),
	(null, 'Fissure', null, null, null, null, null, ''),
	(null, 'Flamethrower', null, null, null, null, null, ''),
	(null, 'Flash', null, null, null, null, null, ''),
	(null, 'Fly', null, null, null, null, null, ''),
	(null, 'Focus Energy', null, null, null, null, null, ''),
	(null, 'Fury Attack', null, null, null, null, null, ''),
	(null, 'Fury Swipes', null, null, null, null, null, ''),
	(null, 'Glare', null, null, null, null, null, ''),
	(null, 'Growl', null, null, null, null, null, ''),
	(null, 'Growth', null, null, null, null, null, ''),
	(null, 'Guillotine', null, null, null, null, null, ''),
	(null, 'Gust', null, null, null, null, null, ''),
	(null, 'Harden', null, null, null, null, null, ''),
	(null, 'Haze', null, null, null, null, null, ''),
	(null, 'Headbutt', null, null, null, null, null, ''),
	(null, 'High Jump Kick', null, null, null, null, null, ''),
	(null, 'Horn Attack', null, null, null, null, null, ''),
	(null, 'Horn Drill', null, null, null, null, null, ''),
	(null, 'Hydro Pump', null, null, null, null, null, ''),
	(null, 'Hyper Beam', null, null, null, null, null, ''),
	(null, 'Hyper Fang', null, null, null, null, null, ''),
	(null, 'Hypnosis', null, null, null, null, null, ''),
	(null, 'Ice Beam', null, null, null, null, null, ''),
	(null, 'Ice Punch', null, null, null, null, null, ''),
	(null, 'Jump Kick', null, null, null, null, null, ''),
	(null, 'Karate Chop', null, null, null, null, null, ''),
	(null, 'Kinesis', null, null, null, null, null, ''),
	(null, 'Leech Life', null, null, null, null, null, ''),
	(null, 'Leech Seed', null, null, null, null, null, ''),
	(null, 'Leer', null, null, null, null, null, ''),
	(null, 'Lick', null, null, null, null, null, ''),
	(null, 'Light Screen', null, null, null, null, null, ''),
	(null, 'Lovely Kiss', null, null, null, null, null, ''),
	(null, 'Low Kick', null, null, null, null, null, ''),
	(null, 'Meditate', null, null, null, null, null, ''),
	(null, 'Mega Drain', null, null, null, null, null, ''),
	(null, 'Mega Kick', null, null, null, null, null, ''),
	(null, 'Mega Punch', null, null, null, null, null, ''),
	(null, 'Metronome', null, null, null, null, null, ''),
	(null, 'Mimic', null, null, null, null, null, ''),
	(null, 'Minimize', null, null, null, null, null, ''),
	(null, 'Mirror Move', null, null, null, null, null, ''),
	(null, 'Mist', null, null, null, null, null, ''),
	(null, 'Night Shade', null, null, null, null, null, ''),
	(null, 'Pay Day', null, null, null, null, null, ''),
	(null, 'Peck', null, null, null, null, null, ''),
	(null, 'Petal Dance', null, null, null, null, null, ''),
	(null, 'Pin Missile', null, null, null, null, null, ''),
	(null, 'Poison Gas', null, null, null, null, null, ''),
	(null, 'Poison Powder', null, null, null, null, null, ''),
	(null, 'Poison Sting', null, null, null, null, null, ''),
	(null, 'Pound', null, null, null, null, null, ''),
	(null, 'Psybeam', null, null, null, null, null, ''),
	(null, 'Psychic', null, null, null, null, null, ''),
	(null, 'Psywave', null, null, null, null, null, ''),
	(null, 'Quick Attack', null, null, null, null, null, ''),
	(null, 'Rage', null, null, null, null, null, ''),
	(null, 'Razor Leaf', null, null, null, null, null, ''),
	(null, 'Razor Wind', null, null, null, null, null, ''),
	(null, 'Recover', null, null, null, null, null, ''),
	(null, 'Reflect', null, null, null, null, null, ''),
	(null, 'Rest', null, null, null, null, null, ''),
	(null, 'Roar', null, null, null, null, null, ''),
	(null, 'Rock Slide', null, null, null, null, null, ''),
	(null, 'Rock Throw', null, null, null, null, null, ''),
	(null, 'Rolling Kick', null, null, null, null, null, ''),
	(null, 'Sand Attack', null, null, null, null, null, ''),
	(null, 'Scratch', null, null, null, null, null, ''),
	(null, 'Screech', null, null, null, null, null, ''),
	(null, 'Seismic Toss', null, null, null, null, null, ''),
	(null, 'Self-Destruct', null, null, null, null, null, ''),
	(null, 'Sharpen', null, null, null, null, null, ''),
	(null, 'Sing', null, null, null, null, null, ''),
	(null, 'Skull Bash', null, null, null, null, null, ''),
	(null, 'Sky Attack', null, null, null, null, null, ''),
	(null, 'Slam', null, null, null, null, null, ''),
	(null, 'Slash', null, null, null, null, null, ''),
	(null, 'Sleep Powder', null, null, null, null, null, ''),
	(null, 'Sludge', null, null, null, null, null, ''),
	(null, 'Smog', null, null, null, null, null, ''),
	(null, 'Smokescreen', null, null, null, null, null, ''),
	(null, 'Soft-Boiled', null, null, null, null, null, ''),
	(null, 'Solar Beam', null, null, null, null, null, ''),
	(null, 'Sonic Boom', null, null, null, null, null, ''),
	(null, 'Spike Cannon', null, null, null, null, null, ''),
	(null, 'Splash', null, null, null, null, null, ''),
	(null, 'Spore', null, null, null, null, null, ''),
	(null, 'Stomp', null, null, null, null, null, ''),
	(null, 'Strength', null, null, null, null, null, ''),
	(null, 'String Shot', null, null, null, null, null, ''),
	(null, 'Struggle', null, null, null, null, null, ''),
	(null, 'Stun Spore', null, null, null, null, null, ''),
	(null, 'Submission', null, null, null, null, null, ''),
	(null, 'Substitute', null, null, null, null, null, ''),
	(null, 'Super Fang', null, null, null, null, null, ''),
	(null, 'Supersonic', null, null, null, null, null, ''),
	(null, 'Surf', null, null, null, null, null, ''),
	(null, 'Swift', null, null, null, null, null, ''),
	(null, 'Swords Dance', null, null, null, null, null, ''),
	(null, 'Tackle', null, null, null, null, null, ''),
	(null, 'Tail Whip', null, null, null, null, null, ''),
	(null, 'Take Down', null, null, null, null, null, ''),
	(null, 'Teleport', null, null, null, null, null, ''),
	(null, 'Thrash', null, null, null, null, null, ''),
	(null, 'Thunder', null, null, null, null, null, ''),
	(null, 'Thunder Punch', null, null, null, null, null, ''),
	(null, 'Thunder Shock', null, null, null, null, null, ''),
	(null, 'Thunder Wave', null, null, null, null, null, ''),
	(null, 'Thunderbolt', null, null, null, null, null, ''),
	(null, 'Toxic', null, null, null, null, null, ''),
	(null, 'Transform', null, null, null, null, null, ''),
	(null, 'Tri Attack', null, null, null, null, null, ''),
	(null, 'Twineedle', null, null, null, null, null, ''),
	(null, 'Vice Grip', null, null, null, null, null, ''),
	(null, 'Vine Whip', null, null, null, null, null, ''),
	(null, 'Water Gun', null, null, null, null, null, ''),
	(null, 'Waterfall', null, null, null, null, null, ''),
	(null, 'Whirlwind', null, null, null, null, null, ''),
	(null, 'Wing Attack', null, null, null, null, null, ''),
	(null, 'Withdraw', null, null, null, null, null, ''),
	(null, 'Wrap', null, null, null, null, null, '');