insert into tbmovimento values
	(null, 'Absorb', 5, 2, 20, 100, 25, 'Rouba metade do dano causado'),
	(null, 'Acid', 8, 2, 40, 100, 30, 'Um ataque que pode diminuir a defesa'),
	(null, 'Acid Armor', 8, 3, null, null, 20, 'Aumenta bem a defesa do usuário'),
	(null, 'Agility', 11, 3, null, null, 30, 'Aumenta bem a velocidade do usuário'),
	(null, 'Amnesia', 11, 3, null, null, 20, 'Aumenta bem a defesa especial do usuário'),
	(null, 'Aurora Beam', 6, 2, 65, 100, 20, 'Um ataque que pode diminuir o ataque'),
	(null, 'Barrage', 1, 1, 15, 85, 20, 'Lança esferas acertando de 2-5 vezes'),
	(null, 'Barrier', 11, 3, null, null, 20, 'Aumenta bem a defesa do usuário'),
	(null, 'Bide', 1, 1, null, null, 10, 'Espera por 2-3 turnos e devolve golpes em dobro'),
	(null, 'Bind', 1, 1, 15, 85, 20, 'Amarra o alvo por 2-5 turnos'),
	(null, 'Bite', 16, 1, 60, 100, 25, 'Um ataque que pode causar flinching (acovardar-se)'),
	(null, 'Blizzard', 6, 2, 110, 70, 5, 'Um ataque que pode congelar o oponente'),
	(null, 'Body Slam', 1, 1, 85, 100, 15, 'Um ataque que pode paralisar'),
	(null, 'Bone Club', 9, 1, 65, 85, 20, 'Um ataque que pode causar flinching (acovardar-se)'),
	(null, 'Bonemerang', 9, 1, 50, 90, 10, 'Um ataque que atinge duas vezes'),
	(null, 'Bubble', 3, 2, 40, 100, 30, 'Um ataque que poderá reduzir a velocidade'),
	(null, 'Bubble Beam', 3, 2, 65, 100, 20, 'Um ataque que pode diminuir a velocidade'),
	(null, 'Clamp', 3, 1, 35, 85, 10, 'Amarra o oponente por 2-5 turnos'),
	(null, 'Comet Punch', 1, 1, 18, 85, 15, 'Repetidos socos de 2-5 vezes'),
	(null, 'Confuse Ray', 8, 3, null, 100, 10, 'Um golpe que causa confusão'),
	(null, 'Confusion', 11, 2, 50, 100, 25, 'Um ataque que pode causar confusão'),
	(null, 'Constrict', 1, 1, 10, 100, 35, 'Um ataque que pode diminuir a velocidade'),
	(null, 'Conversion', 1, 3, null, null, 30, 'Muda o tipo do usuário para o tipo do golpe'),
	(null, 'Counter', 7, 1, null, 100, 20, 'Devolve um golpe físico redobrado'),
	(null, 'Crabhammer', 3, 1, 100, 90, 10, 'Tem uma grande chance de ser um golpe crítico'),
	(null, 'Cut', 1, 1, 50, 95, 30, 'Corta usando garras, foice, etc.'),
	(null, 'Defense Curl', 1, 3, null, null, 40, 'Aumenta a defesa do usuário'),
	(null, 'Dig', 9, 1, 80, 100, 10, '1º turno: se enterra, 2º turno: ataca'),
	(null, 'Disable', 1, 3, null, 100, 20, 'Desabilita o mais recente movimento do adversário'),
	(null, 'Dizzy Punch', 1, 1, 70, 100, 10, 'Um ataque que poderá confundir'),
	(null, 'Double Kick', 7, 1, 30, 100, 30, 'Um ataque de chute duplo'),
	(null, 'Double Slap', 1, 1, 15, 85, 10, 'Repetidos tapas de 2-5 vezes'),
	(null, 'Double Team', 1, 3, null, null, 15, 'Aumenta a chance de escapar de um golpe'),
	(null, 'Double-Edge', 1, 1, 120, 100, 15, 'Um ataque que também machuca o usuário'),
	(null, 'Dragon Rage', 15, 2, null, 100, 10, 'Sempre causa 40HP de dano'),
	(null, 'Dream Eater', 11, 2, 100, 100, 15, 'Rouba HP de uma vitima dormindo'),
	(null, 'Drill Peck', 10, 1, 80, 100, 20, 'Um forte ataque de bicada giratório'),
	(null, 'Earthquake', 9, 1, 100, 100, 10, 'Forte, mas inútil contra oponentes voadores'),
	(null, 'Egg Bomb', 1, 1, 100, 75, 10, 'Ovos são lançados no oponente'),
	(null, 'Ember', 2, 2, 40, 100, 25, 'Um ataque que pode causar um incêndio'),
	(null, 'Explosion', 1, 1, 250, 100, 5, 'Muito poderoso, mas derrota o usuário'),
	(null, 'Fire Blast', 2, 2, 110, 85, 5, 'Um ataque que pode incendiar'),
	(null, 'Fire Punch', 2, 1, 75, 100, 15, 'Um soco ardente. Poderá incendiar'),
	(null, 'Fire Spin', 2, 2, 35, 85, 15, 'Prende o inimigo no fogo por 2-5 turnos'),
	(null, 'Fissure', 9, 1, null, null, 5, 'KO em um golpe'),
	(null, 'Flamethrower', 2, 2, 90, 100, 15, 'Um ataque que pode causar um incêndio'),
	(null, 'Flash', 1, 3, null, 100, 20, 'Cega o oponente para reduzir a precisão'),
	(null, 'Fly', 10, 1, 90, 95, 15, '1º turno: voa, 2º turno: ataca'),
	(null, 'Focus Energy', 1, 3, null, null, 30, 'Aumenta a chance de o golpe ser crítico'),
	(null, 'Fury Attack', 1, 1, 15, 85, 20, 'Golpeia o alvo 2-5 vezes'),
	(null, 'Fury Swipes', 1, 1, 18, 80, 15, 'Arranha rapidamente por 2-5 vezes'),
	(null, 'Glare', 1, 3, null, 100, 30, 'Um golpe que poderá paralisar'),
	(null, 'Growl', 1, 3, null, 100, 40, 'Reduz o ataque do oponente'),
	(null, 'Growth', 1, 3, null, null, 40, 'Aumenta o nível de S. Attack '),
	(null, 'Guillotine', 1, 1, null, null, 5, 'KO em um golpe, ataque de pinça'),
	(null, 'Gust', 10, 2, 40, 100, 35, 'Manda uma grande rajada de vento'),
	(null, 'Harden', 1, 3, null, null, 30, 'Aumenta a defesa do usuário'),
	(null, 'Haze', 6, 3, null, null, 30, 'Elimina todas as mudanças de estado'),
	(null, 'Headbutt', 1, 1, 70, 100, 15, 'Um ataque que pode acovardar o inimigo'),
	(null, 'High Jump Kick', 7, 1, 130, 90, 10, 'Pode errar e causar dano ao usuário'),
	(null, 'Horn Attack', 1, 1, 65, 100, 25, 'Um ataque que usa o chifre para golpear'),
	(null, 'Horn Drill', 1, 1, null, null, 5, 'KO em um golpe, ataque de perfuração'),
	(null, 'Hydro Pump', 3, 2, 110, 80, 5, 'Um poderoso ataque do tipo água'),
	(null, 'Hyper Beam', 1, 2, 150, 90, 5, '1º turno: ataca, 2º turno: descansa'),
	(null, 'Hyper Fang', 1, 1, 80, 90, 15, 'Um ataque que pode causar flinching (acovardar-se)'),
	(null, 'Hypnosis', 11, 3, null, 60, 20, 'Poderá coloca o oponente para dormir'),
	(null, 'Ice Beam', 6, 2, 90, 100, 10, 'Um ataque que pode congelar o oponente'),
	(null, 'Ice Punch', 6, 1, 75, 100, 15, 'Um soco gelado. Poderá congelar'),
	(null, 'Jump Kick', 7, 1, 100, 95, 10, 'Pode errar, dando dano ao usuário'),
	(null, 'Karate Chop', 7, 1, 50, 100, 25, 'Tem uma grande chance de ser um golpe crítico'),
	(null, 'Kinesis', 11, 3, null, 80, 15, 'Diminui a precisão do oponente'),
	(null, 'Leech Life', 12, 1, 80, 100, 10, 'Rouba metade do dano causado'),
	(null, 'Leech Seed', 5, 3, null, 90, 10, 'Rouba HP do oponente a cada turno'),
	(null, 'Leer', 1, 3, null, 100, 30, 'Reduz a defesa do oponente'),
	(null, 'Lick', 14, 1, 30, 100, 30, 'Um ataque que poderá paralisar'),
	(null, 'Light Screen', 11, 3, null, null, 30, 'Aumenta a defesa especial com uma parede de luz'),
	(null, 'Lovely Kiss', 1, 3, null, 75, 10, 'Poderá fazer com que o oponente durma'),
	(null, 'Low Kick', 7, 1, null, 100, 20, 'Um ataque que pode causar flinching (acovardar-se)'),
	(null, 'Meditate', 11, 3, null, null, 40, 'Aumenta o ataque do usuário'),
	(null, 'Mega Drain', 5, 2, 40, 100, 15, 'Rouba metade do dano causado'),
	(null, 'Mega Kick', 1, 1, 120, 75, 5, 'Um ataque de chute forte'),
	(null, 'Mega Punch', 1, 1, 80, 85, 20, 'Um poderoso soco lançado muito forte'),
	(null, 'Metronome', 1, 3, null, null, 10, 'Escolhe ao acaso um dos golpes Pokémons'),
	(null, 'Mimic', 1, 3, null, null, 10, 'Copia um golpe usado pelo oponente'),
	(null, 'Minimize', 1, 3, null, null, 10, 'Aumenta a chance de escapar de um golpe'),
	(null, 'Mirror Move', 10, 3, null, null, 20, 'Devolve o ataque com o mesmo golpe'),
	(null, 'Mist', 6, 3, null, null, 30, 'Previne redução de status'),
	(null, 'Night Shade', 14, 2, null, 100, 15, 'O nível do usuário iguala ao HP de dano'),
	(null, 'Pay Day', 1, 1, 40, 100, 20, 'Joga suas moedas. Tem elas de volta mais tarde'),
	(null, 'Peck', 10, 1, 35, 100, 35, 'Golpeia o inimigo com um bico, etc'),
	(null, 'Petal Dance', 5, 2, 120, 100, 10, 'Funciona por 2-3 turnos e confunde o usuário'),
	(null, 'Pin Missile', 12, 1, 25, 95, 20, 'Lança alfinetes que atingem 2-5 vezes'),
	(null, 'Poison Gas', 8, 3, null, 90, 40, 'Um golpe que poderá envenenar o oponente'),
	(null, 'Poison Powder', 8, 3, null, 75, 35, 'Um golpe que pode envenenar o oponente'),
	(null, 'Poison Sting', 8, 1, 15, 100, 35, 'Um ataque que pode envenenar o alvo'),
	(null, 'Pound', 1, 1, 40, 100, 35, 'Golpeia com as pernas da frente ou com o rabo'),
	(null, 'Psybeam', 11, 2, 65, 100, 20, 'Um ataque que pode confundir o oponente'),
	(null, 'Psychic', 11, 2, 90, 100, 10, 'Um ataque que pode diminuir a defesa especial'),
	(null, 'Psywave', 11, 2, null, 80, 15, 'Um ataque que varia seu poder'),
	(null, 'Quick Attack', 1, 1, 40, 100, 30, 'Permite que o usuário ataque primeiro'),
	(null, 'Rage', 1, 1, 20, 100, 20, 'Aumenta o ataque do usuário se golpeado'),
	(null, 'Razor Leaf', 5, 1, 55, 95, 25, 'Tem uma grande chance de ser um golpe crítico'),
	(null, 'Razor Wind', 1, 2, 80, 100, 10, '1º turno: prepara, 2º turno: ataca'),
	(null, 'Recover', 1, 3, null, null, 10, 'Recupera a HP em metade da HP máxima'),
	(null, 'Reflect', 11, 3, null, null, 20, 'Aumenta a defesa com uma barreira'),
	(null, 'Rest', 11, 3, null, null, 10, 'Dorme por 2 turnos para recuperar toda a HP'),
	(null, 'Roar', 1, 3, null, null, 20, '	Assusta inimigos selvagens e acaba com a batalha'),
	(null, 'Rock Slide', 13, 1, 75, 90, 10, 'Um ataque que pode causar flinching (acovardar-se)'),
	(null, 'Rock Throw', 13, 1, 50, 90, 15, 'Solta pedras no inimigo'),
	(null, 'Rolling Kick', 7, 1, 60, 85, 15, 'Um chute rápido e giratório'),
	(null, 'Sand Attack', 9, 3, null, 100, 15, 'Reduz a chance de acertar lançando areia'),
	(null, 'Scratch', 1, 1, 40, 100, 35, 'Arranha com garras afiadas'),
	(null, 'Screech', 1, 3, null, 85, 40, 'Reduz bem a defesa do oponente'),
	(null, 'Seismic Toss', 7, 1, null, 100, 20, 'O nível do usuários equivale ao dano'),
	(null, 'Self-Destruct', 1, 1, 200, 100, 5, 'Poderoso, mas derrota o usuário'),
	(null, 'Sharpen', 1, 3, null, null, 30, 'Um golpe que poderá aumentar o ataque'),
	(null, 'Sing', 1, 3, null, 55, 15, 'Pode fazer com que o inimigo durma'),
	(null, 'Skull Bash', 1, 1, 130, 100, 10, '1º turno: prepara, 2º turno: ataca'),
	(null, 'Sky Attack', 10, 1, 140, 90, 5, '1º turno: prepara, 2º turno: ataca'),
	(null, 'Slam', 1, 1, 80, 75, 20, 'Acerta o inimigo com o rabo, vinha, etc'),
	(null, 'Slash', 1, 1, 70, 100, 20, 'Tem uma grande chance de ser um golpe crítico'),
	(null, 'Sleep Powder', 5, 3, null, 75, 15, 'Pode fazer com que o oponente durma'),
	(null, 'Sludge', 8, 2, 65, 100, 20, 'Um ataque que poderá envenenar'),
	(null, 'Smog', 8, 2, 30, 70, 20, 'Um ataque que poderá envenenar'),
	(null, 'Smokescreen', 1, 3, null, 100, 20, 'Diminui a precisão do oponente'),
	(null, 'Soft-Boiled', 1, 3, null, null, 10, 'Recupera a HP em metade do máximo de HP'),
	(null, 'Solar Beam', 5, 2, 120, 100, 10, '1º turno: preparar, 2º turno: ataca'),
	(null, 'Sonic Boom', 1, 2, null, 90, 20, 'Sempre causa 20HP de dano'),
	(null, 'Spike Cannon', 1, 1, 20, 100, 15, 'Lança espinhos acertando 2-5 vezes'),
	(null, 'Splash', 1, 3, null, null, 40, 'Não tem nenhum efeito'),
	(null, 'Spore', 5, 3, null, 100, 15, 'Um golpe que estimula o sono'),
	(null, 'Stomp', 1, 1, 65, 100, 20, 'Um ataque que pode causar flinching (acovardar-se)'),
	(null, 'Strength', 1, 1, 80, 100, 15, 'Um poderoso ataque físico'),
	(null, 'String Shot', 12, 3, null, 95, 40, 'Um golpe que diminui a velocidade do oponente'),
	(null, 'Struggle', 1, 1, 50, 100, null, 'Usado somente se toda a PP tiver acabado'),
	(null, 'Stun Spore', 5, 3, null, 75, 30, 'Um golpe que pode paralisar o oponente'),
	(null, 'Submission', 7, 1, 80, 80, 20, 'Um ataque que também machuca o usuário'),
	(null, 'Substitute', 1, 3, null, null, 10, 'Faz uma isca com 1/4 da HP max. do usuário'),
	(null, 'Super Fang', 1, 1, null, 90, 10, 'Reduz a HP do oponente em metade'),
	(null, 'Supersonic', 1, 3, null, 55, 20, 'Ondas sonoras que causam confusão'),
	(null, 'Surf', 3, 2, 90, 100, 15, 'Um forte ataque do tipo água'),
	(null, 'Swift', 1, 2, 60, null, 20, 'Um ataque que nunca erra'),
	(null, 'Swords Dance', 1, 3, null, null, 20, 'Uma dança que aumenta o Ataque'),
	(null, 'Tackle', 1, 1, 40, 100, 35, 'Um ataque de agressão com o corpo todo'),
	(null, 'Tail Whip', 1, 3, null, 100, 30, 'Diminui a defesa do inimigo'),
	(null, 'Take Down', 1, 1, 90, 85, 20, 'Um ataque que também machuca o usuário'),
	(null, 'Teleport', 11, 3, null, null, 20, 'Um golpe para escapar de uma batalha'),
	(null, 'Thrash', 1, 1, 120, 100, 10, 'Funciona durante 2-3 rodadas e confunde o usuário'),
	(null, 'Thunder', 4, 2, 110, 70, 10, 'Um ataque que pode paralisar'),
	(null, 'Thunder Punch', 4, 1, 75, 100, 15, 'Um soco elétrico. Poderá paralisar'),
	(null, 'Thunder Shock', 4, 2, 40, 100, 30, 'Um ataque que pode paralisar'),
	(null, 'Thunder Wave', 4, 3, null, 90, 20, 'Um golpe que pode paralisar'),
	(null, 'Thunderbolt', 4, 2, 90, 100, 15, 'Um ataque que pode paralisar'),
	(null, 'Toxic', 8, 3, null, 90, 10, 'Um golpe com dano crescente'),
	(null, 'Transform', 1, 3, null, null, 10, 'O usuário assume uma cópia do adversário'),
	(null, 'Tri Attack', 1, 2, 80, 100, 10, 'Lança três tipos de raios de uma vez'),
	(null, 'Twineedle', 12, 1, 25, 100, 20, 'Golpeia o inimigo duas vezes usando ferrões'),
	(null, 'Vice Grip', 1, 1, 55, 100, 30, 'Agarra com poderosas pinças'),
	(null, 'Vine Whip', 5, 1, 45, 100, 25, 'Chicoteia o inimigo finas vinhas'),
	(null, 'Water Gun', 3, 2, 40, 100, 25, 'Respinga água para atacar'),
	(null, 'Waterfall', 3, 1, 80, 100, 15, 'Um golpe aquático'),
	(null, 'Whirlwind', 1, 3, null, null, 20, 'Manda para longe seu inimigo + acaba a batalha'),
	(null, 'Wing Attack', 10, 1, 60, 100, 35, 'Acerta o alvo com as asas'),
	(null, 'Withdraw', 3, 3, null, null, 40, 'Aumenta a defesa do usuário'),
	(null, 'Wrap', 1, 1, 15, 90, 20, 'Espreme o inimigo por 2-5 turnos');